# This is a basic workflow that is manually triggered
name: Run Playwright Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: 'demo.s1'
      testFiles:
        description: 'Specify Test Files or Folder (will run all if empty)'
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  RunPlaywrightTests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '18.x'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install the specified version of Node.js
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install npm packages.
      - name: Install npm packages
        run: npm ci

      # Run EsLint.
      - name: Run EsLint
        run: npm run lint

      # Run Build Project.
      - name: Build Project
        run: npm run build

      # Install Playwright browsers.
      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps chromium
          npx playwright install --with-deps chrome

      # Set environment variables
      - name: Set environment variable
        run: echo "ENV=${{ inputs.environment }}" > config/.env && cat config/.env

      # Run Playwright tests
      - name: Run Playwright Tests
        run: |
          echo "Test Files: ${{ inputs.testFiles }}"
          npx playwright test ${{ inputs.testFiles }}

      # Publish the JUnit test results.
      - name: Publish test results
        run: |
          echo "test_results_path=./test-JUNIT/results.xml" >> $GITHUB_OUTPUT

      # Publish the Playwright report as a pipeline artifact.
      - name: Publish Test Results Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./playwright-report/
          retention-days: 30
          
      - if: always()
        uses: actions/upload-artifact@master
        with:
          name: test-report.html
          path: ./playwright-report/index.html